# Generated by Django 5.0.6 on 2024-07-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.EmailField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'books',
                'managed': True,
            },
        ),
    ]
