# Generated by Django 5.0.6 on 2024-07-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_books_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
