# Generated by Django 5.0.6 on 2024-07-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_borrowbook_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
